import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import LayoutWrapper from "@/components/layout-wrapper";
import { Toaster } from "sonner";
import ArticleNoticeProvider from "./articles/article-notice-provider";
import { auth } from "@/server/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ArticleNoticeProvider>
          <SessionProvider>
            {session?.user && (
              <LayoutWrapper>
                <Toaster richColors />
                {children}
              </LayoutWrapper>
            )}
            {!session?.user && children}
          </SessionProvider>
        </ArticleNoticeProvider>
      </body>
    </html>
  );
}
